services:
  - type: web
    name: laravel-app
    env: docker
    repo: https://github.com/your-username/your-laravel-repo
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase: mysql-database
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        fromDatabase: mysql-database
      - key: DB_USERNAME
        fromDatabase: mysql-database
      - key: DB_PASSWORD
        fromDatabase: mysql-database

databases:
  - name: mysql-database
    plan: free
    databaseName: your-database-name
    user: your-username
